[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600
; upload_port = COM10
; monitor_port = COM10
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_src_filter =
    +<*>
    -<Calibration.ino>
    -<Testing.ino>
    -<loadcell_node.cpp>
build_flags =
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_SUPPORT=1
    -mfix-esp32-psram-cache-issue
lib_deps =
    moononournation/GFX Library for Arduino@1.5.6
    tamctec/TAMC_GT911
    bblanchon/ArduinoJson
    ricmoo/QRCode

[env:scale_node]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
    +<loadcell_node.cpp>
    +<HX711_ADC.cpp>

