[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<*>
    -<Calibration.ino>
    -<Testing.ino>
    -<loadcell_node.cpp>
build_flags =
    -D USER_SETUP_LOADED
    -include src/user_setup.h
lib_deps =
    bodmer/TFT_eSPI
    paulstoffregen/XPT2046_Touchscreen
    bblanchon/ArduinoJson

[env:scale_node]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
    +<loadcell_node.cpp>
    +<HX711_ADC.cpp>

